
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=create-drop

spring.cache.type=none

spring.task.scheduling.pool.size=0

app.payment-api.url=http://localhost:8089

logging.level.root=INFO

logging.level.org.testcontainers=WARN
logging.level.org.apache.http=WARN